version: '3.9'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperS3cr3t!
      - MSSQL_DATABASE=TMS_DEV
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  sql_data:
    driver: local
